import './globals.scss';
import { Inter } from 'next/font/google';
import { cookies } from 'next/headers';
import Link from 'next/link';
import { ReactNode } from 'react';
import { getUserBySessionToken } from '../database/users';
import { LogoutButton } from './(auth)/logout/LogoutButton';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

type Props = {
  children: ReactNode;
};

export default async function RootLayout({ children }: Props) {
  // 1. get the session token from the cookie
  const cookieStore = cookies();
  const sessionToken = cookieStore.get('sessionToken');

  const user = !sessionToken?.value
    ? undefined
    : await getUserBySessionToken(sessionToken.value);

  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
          {user ? (
            <div>
              <div>
                <Link href="/activity">Feed</Link>
              </div>
              {/* how to get firstname here? user.firstname */}
              <span>Hello, </span>
              <Link href="/profile">{user.firstname}</Link>
              <LogoutButton />
            </div>
          ) : (
            <div>
              <Link href="/login">Log in</Link>
              <br />
              <Link href="/signup">Sign up</Link>
            </div>
          )}
        </div>
        {children}
      </body>
    </html>
  );
}
