import { Inter } from 'next/font/google';
import { cookies } from 'next/headers';
import Link from 'next/link';
import { ReactNode } from 'react';
import { GrHomeRounded } from 'react-icons/gr';
import { LogoutButton } from '../../app/(auth)/logout/LogoutButton';
import { getUserBySessionToken } from '../../database/users';
import styles from './layout.module.scss';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

type Props = {
  children: ReactNode;
};

export default async function RootLayout({ children }: Props) {
  // 1. get the session token from the cookie
  const cookieStore = cookies();
  const sessionToken = cookieStore.get('sessionToken');

  const user = !sessionToken?.value
    ? undefined
    : await getUserBySessionToken(sessionToken.value);

  return (
    <html lang="en">
      <body className={inter.className}>
        <main>
          {user ? (
            <div className={styles.profileNavbar}>
              <div>
                <Link href="/activity">
                  <GrHomeRounded size="1.65rem" />
                </Link>
              </div>
              {/* how to get firstname here? user.firstname */}
              <div>
                <span className={styles.helloUsername}>Hello </span>

                <Link className={styles.helloUsername} href="/profile">
                  {user.firstname}
                </Link>
              </div>
              <span>
                <LogoutButton />
              </span>
            </div>
          ) : (
            <div>
              <Link href="/login">Log in</Link>
              <br />
              <Link href="/signup">Sign up</Link>
            </div>
          )}
        </main>
        {children}
      </body>
    </html>
  );
}
