import { Inter } from 'next/font/google';
import { cookies } from 'next/headers';
import Link from 'next/link';
import { ReactNode } from 'react';
import { CgProfile } from 'react-icons/cg';
import { GrHomeRounded } from 'react-icons/gr';
import { LogoutButton } from '../(auth)/logout/LogoutButton';
import { getUserBySessionToken } from '../../database/users';
import styles from './layout.module.scss';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

type Props = {
  children: ReactNode;
};

export default async function RootLayout({ children }: Props) {
  // 1. get the session token from the cookie
  const cookieStore = cookies();
  const sessionToken = cookieStore.get('sessionToken');

  const user = !sessionToken?.value
    ? undefined
    : await getUserBySessionToken(sessionToken.value);

  return (
    <html lang="en">
      <body className={inter.className}>
        <section>
          {user ? (
            <div className={styles.feedNavbar}>
              <Link href="/activity">
                <GrHomeRounded size="1.65rem" />
              </Link>
              <div>
                {/* <span>Hello </span> */}

                {/* <Link href="/profile">{user.firstname}</Link> */}
                <Link href="/profile">
                  <CgProfile size="1.8rem" color="#000" />
                </Link>
              </div>
              <LogoutButton />
            </div>
          ) : (
            <div>
              <Link href="/login">Log in</Link>
              <br />
              <Link href="/signup">Sign up</Link>
            </div>
          )}
        </section>
        {children}
      </body>
    </html>
  );
}
